      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            pip install pytest pytest-cov
      # Step 3: run linter and tests
      - run:
          name: run tests